#include<iostream>
#include<fstream>
#include <cstdlib>
#include <string>
#include "radix.h"
#include "stack.h"
#include "inputFunctions.h"
#include "sort.h"

using namespace std;

int main(int argc, char *argv[]) {
    uint64_t count1=0,count2=0;
    struct mytuple *array1,*array2,*_array1,*_array2;
    int n=25;
    string filename;
    //run under build dir generated by cmake
	filename=argv[1];
//    if(argc>1)
//		filename=argv[1];
//    if(argc>2){
//		n=stoi(argv[2]);
//		if(2<<(n-1)<0)
//			n=20;
//	}
    if(!getArraySize(filename,count1,count2)) {
        cout<<"could not open file.\n";
        exit(-1);
    }
    array1=new mytuple[count1];
    array2=new mytuple[count2];
    if(!makearrays(filename,array1,array2)) {
        cout<<"could not open file.\n";
        exit(-1);
    }
    _array1=new mytuple[count1];
    _array2=new mytuple[count2];
    radix r1(0,count1,array1,_array1,1);
    sort(&r1);
    radix r2(0,count2,array2,_array2,1);
    sort(&r2);
    list *resultlist=finalresults(array1,array2,count1,count2);
    resultlist->print();
    delete[] array1;
    delete[] array2;
    delete[] _array1;
    delete[] _array2;
    delete resultlist;
    return 0;
}
