# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/clion-2019.1/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /opt/clion-2019.1/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/efstratia/Documents/di/examino 7/Project/Project2019"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/efstratia/Documents/di/examino 7/Project/Project2019"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/clion-2019.1/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/opt/clion-2019.1/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/efstratia/Documents/di/examino 7/Project/Project2019/CMakeFiles" "/home/efstratia/Documents/di/examino 7/Project/Project2019/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/efstratia/Documents/di/examino 7/Project/Project2019/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_bitmap

# Build rule for target.
test_bitmap: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_bitmap
.PHONY : test_bitmap

# fast build rule for target.
test_bitmap/fast:
	$(MAKE) -f CMakeFiles/test_bitmap.dir/build.make CMakeFiles/test_bitmap.dir/build
.PHONY : test_bitmap/fast

#=============================================================================
# Target rules for targets named test_radix

# Build rule for target.
test_radix: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_radix
.PHONY : test_radix

# fast build rule for target.
test_radix/fast:
	$(MAKE) -f CMakeFiles/test_radix.dir/build.make CMakeFiles/test_radix.dir/build
.PHONY : test_radix/fast

#=============================================================================
# Target rules for targets named Project2019

# Build rule for target.
Project2019: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Project2019
.PHONY : Project2019

# fast build rule for target.
Project2019/fast:
	$(MAKE) -f CMakeFiles/Project2019.dir/build.make CMakeFiles/Project2019.dir/build
.PHONY : Project2019/fast

#=============================================================================
# Target rules for targets named test_relations

# Build rule for target.
test_relations: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_relations
.PHONY : test_relations

# fast build rule for target.
test_relations/fast:
	$(MAKE) -f CMakeFiles/test_relations.dir/build.make CMakeFiles/test_relations.dir/build
.PHONY : test_relations/fast

#=============================================================================
# Target rules for targets named test_jobscheduler

# Build rule for target.
test_jobscheduler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_jobscheduler
.PHONY : test_jobscheduler

# fast build rule for target.
test_jobscheduler/fast:
	$(MAKE) -f CMakeFiles/test_jobscheduler.dir/build.make CMakeFiles/test_jobscheduler.dir/build
.PHONY : test_jobscheduler/fast

#=============================================================================
# Target rules for targets named test_join

# Build rule for target.
test_join: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_join
.PHONY : test_join

# fast build rule for target.
test_join/fast:
	$(MAKE) -f CMakeFiles/test_join.dir/build.make CMakeFiles/test_join.dir/build
.PHONY : test_join/fast

#=============================================================================
# Target rules for targets named test_queue

# Build rule for target.
test_queue: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_queue
.PHONY : test_queue

# fast build rule for target.
test_queue/fast:
	$(MAKE) -f CMakeFiles/test_queue.dir/build.make CMakeFiles/test_queue.dir/build
.PHONY : test_queue/fast

JoinArray.o: JoinArray.cpp.o

.PHONY : JoinArray.o

# target to build an object file
JoinArray.cpp.o:
	$(MAKE) -f CMakeFiles/Project2019.dir/build.make CMakeFiles/Project2019.dir/JoinArray.cpp.o
	$(MAKE) -f CMakeFiles/test_join.dir/build.make CMakeFiles/test_join.dir/JoinArray.cpp.o
.PHONY : JoinArray.cpp.o

JoinArray.i: JoinArray.cpp.i

.PHONY : JoinArray.i

# target to preprocess a source file
JoinArray.cpp.i:
	$(MAKE) -f CMakeFiles/Project2019.dir/build.make CMakeFiles/Project2019.dir/JoinArray.cpp.i
	$(MAKE) -f CMakeFiles/test_join.dir/build.make CMakeFiles/test_join.dir/JoinArray.cpp.i
.PHONY : JoinArray.cpp.i

JoinArray.s: JoinArray.cpp.s

.PHONY : JoinArray.s

# target to generate assembly for a file
JoinArray.cpp.s:
	$(MAKE) -f CMakeFiles/Project2019.dir/build.make CMakeFiles/Project2019.dir/JoinArray.cpp.s
	$(MAKE) -f CMakeFiles/test_join.dir/build.make CMakeFiles/test_join.dir/JoinArray.cpp.s
.PHONY : JoinArray.cpp.s

Priority_Queue.o: Priority_Queue.cpp.o

.PHONY : Priority_Queue.o

# target to build an object file
Priority_Queue.cpp.o:
	$(MAKE) -f CMakeFiles/Project2019.dir/build.make CMakeFiles/Project2019.dir/Priority_Queue.cpp.o
	$(MAKE) -f CMakeFiles/test_join.dir/build.make CMakeFiles/test_join.dir/Priority_Queue.cpp.o
.PHONY : Priority_Queue.cpp.o

Priority_Queue.i: Priority_Queue.cpp.i

.PHONY : Priority_Queue.i

# target to preprocess a source file
Priority_Queue.cpp.i:
	$(MAKE) -f CMakeFiles/Project2019.dir/build.make CMakeFiles/Project2019.dir/Priority_Queue.cpp.i
	$(MAKE) -f CMakeFiles/test_join.dir/build.make CMakeFiles/test_join.dir/Priority_Queue.cpp.i
.PHONY : Priority_Queue.cpp.i

Priority_Queue.s: Priority_Queue.cpp.s

.PHONY : Priority_Queue.s

# target to generate assembly for a file
Priority_Queue.cpp.s:
	$(MAKE) -f CMakeFiles/Project2019.dir/build.make CMakeFiles/Project2019.dir/Priority_Queue.cpp.s
	$(MAKE) -f CMakeFiles/test_join.dir/build.make CMakeFiles/test_join.dir/Priority_Queue.cpp.s
.PHONY : Priority_Queue.cpp.s

SQL.o: SQL.cpp.o

.PHONY : SQL.o

# target to build an object file
SQL.cpp.o:
	$(MAKE) -f CMakeFiles/Project2019.dir/build.make CMakeFiles/Project2019.dir/SQL.cpp.o
	$(MAKE) -f CMakeFiles/test_join.dir/build.make CMakeFiles/test_join.dir/SQL.cpp.o
.PHONY : SQL.cpp.o

SQL.i: SQL.cpp.i

.PHONY : SQL.i

# target to preprocess a source file
SQL.cpp.i:
	$(MAKE) -f CMakeFiles/Project2019.dir/build.make CMakeFiles/Project2019.dir/SQL.cpp.i
	$(MAKE) -f CMakeFiles/test_join.dir/build.make CMakeFiles/test_join.dir/SQL.cpp.i
.PHONY : SQL.cpp.i

SQL.s: SQL.cpp.s

.PHONY : SQL.s

# target to generate assembly for a file
SQL.cpp.s:
	$(MAKE) -f CMakeFiles/Project2019.dir/build.make CMakeFiles/Project2019.dir/SQL.cpp.s
	$(MAKE) -f CMakeFiles/test_join.dir/build.make CMakeFiles/test_join.dir/SQL.cpp.s
.PHONY : SQL.cpp.s

SQLInfo.o: SQLInfo.cpp.o

.PHONY : SQLInfo.o

# target to build an object file
SQLInfo.cpp.o:
	$(MAKE) -f CMakeFiles/Project2019.dir/build.make CMakeFiles/Project2019.dir/SQLInfo.cpp.o
	$(MAKE) -f CMakeFiles/test_join.dir/build.make CMakeFiles/test_join.dir/SQLInfo.cpp.o
.PHONY : SQLInfo.cpp.o

SQLInfo.i: SQLInfo.cpp.i

.PHONY : SQLInfo.i

# target to preprocess a source file
SQLInfo.cpp.i:
	$(MAKE) -f CMakeFiles/Project2019.dir/build.make CMakeFiles/Project2019.dir/SQLInfo.cpp.i
	$(MAKE) -f CMakeFiles/test_join.dir/build.make CMakeFiles/test_join.dir/SQLInfo.cpp.i
.PHONY : SQLInfo.cpp.i

SQLInfo.s: SQLInfo.cpp.s

.PHONY : SQLInfo.s

# target to generate assembly for a file
SQLInfo.cpp.s:
	$(MAKE) -f CMakeFiles/Project2019.dir/build.make CMakeFiles/Project2019.dir/SQLInfo.cpp.s
	$(MAKE) -f CMakeFiles/test_join.dir/build.make CMakeFiles/test_join.dir/SQLInfo.cpp.s
.PHONY : SQLInfo.cpp.s

do_query.o: do_query.cpp.o

.PHONY : do_query.o

# target to build an object file
do_query.cpp.o:
	$(MAKE) -f CMakeFiles/Project2019.dir/build.make CMakeFiles/Project2019.dir/do_query.cpp.o
.PHONY : do_query.cpp.o

do_query.i: do_query.cpp.i

.PHONY : do_query.i

# target to preprocess a source file
do_query.cpp.i:
	$(MAKE) -f CMakeFiles/Project2019.dir/build.make CMakeFiles/Project2019.dir/do_query.cpp.i
.PHONY : do_query.cpp.i

do_query.s: do_query.cpp.s

.PHONY : do_query.s

# target to generate assembly for a file
do_query.cpp.s:
	$(MAKE) -f CMakeFiles/Project2019.dir/build.make CMakeFiles/Project2019.dir/do_query.cpp.s
.PHONY : do_query.cpp.s

job.o: job.cpp.o

.PHONY : job.o

# target to build an object file
job.cpp.o:
	$(MAKE) -f CMakeFiles/Project2019.dir/build.make CMakeFiles/Project2019.dir/job.cpp.o
.PHONY : job.cpp.o

job.i: job.cpp.i

.PHONY : job.i

# target to preprocess a source file
job.cpp.i:
	$(MAKE) -f CMakeFiles/Project2019.dir/build.make CMakeFiles/Project2019.dir/job.cpp.i
.PHONY : job.cpp.i

job.s: job.cpp.s

.PHONY : job.s

# target to generate assembly for a file
job.cpp.s:
	$(MAKE) -f CMakeFiles/Project2019.dir/build.make CMakeFiles/Project2019.dir/job.cpp.s
.PHONY : job.cpp.s

jobscheduler.o: jobscheduler.cpp.o

.PHONY : jobscheduler.o

# target to build an object file
jobscheduler.cpp.o:
	$(MAKE) -f CMakeFiles/Project2019.dir/build.make CMakeFiles/Project2019.dir/jobscheduler.cpp.o
	$(MAKE) -f CMakeFiles/test_jobscheduler.dir/build.make CMakeFiles/test_jobscheduler.dir/jobscheduler.cpp.o
.PHONY : jobscheduler.cpp.o

jobscheduler.i: jobscheduler.cpp.i

.PHONY : jobscheduler.i

# target to preprocess a source file
jobscheduler.cpp.i:
	$(MAKE) -f CMakeFiles/Project2019.dir/build.make CMakeFiles/Project2019.dir/jobscheduler.cpp.i
	$(MAKE) -f CMakeFiles/test_jobscheduler.dir/build.make CMakeFiles/test_jobscheduler.dir/jobscheduler.cpp.i
.PHONY : jobscheduler.cpp.i

jobscheduler.s: jobscheduler.cpp.s

.PHONY : jobscheduler.s

# target to generate assembly for a file
jobscheduler.cpp.s:
	$(MAKE) -f CMakeFiles/Project2019.dir/build.make CMakeFiles/Project2019.dir/jobscheduler.cpp.s
	$(MAKE) -f CMakeFiles/test_jobscheduler.dir/build.make CMakeFiles/test_jobscheduler.dir/jobscheduler.cpp.s
.PHONY : jobscheduler.cpp.s

join_preds.o: join_preds.cpp.o

.PHONY : join_preds.o

# target to build an object file
join_preds.cpp.o:
	$(MAKE) -f CMakeFiles/test_join.dir/build.make CMakeFiles/test_join.dir/join_preds.cpp.o
.PHONY : join_preds.cpp.o

join_preds.i: join_preds.cpp.i

.PHONY : join_preds.i

# target to preprocess a source file
join_preds.cpp.i:
	$(MAKE) -f CMakeFiles/test_join.dir/build.make CMakeFiles/test_join.dir/join_preds.cpp.i
.PHONY : join_preds.cpp.i

join_preds.s: join_preds.cpp.s

.PHONY : join_preds.s

# target to generate assembly for a file
join_preds.cpp.s:
	$(MAKE) -f CMakeFiles/test_join.dir/build.make CMakeFiles/test_join.dir/join_preds.cpp.s
.PHONY : join_preds.cpp.s

list.o: list.cpp.o

.PHONY : list.o

# target to build an object file
list.cpp.o:
	$(MAKE) -f CMakeFiles/test_radix.dir/build.make CMakeFiles/test_radix.dir/list.cpp.o
	$(MAKE) -f CMakeFiles/Project2019.dir/build.make CMakeFiles/Project2019.dir/list.cpp.o
	$(MAKE) -f CMakeFiles/test_join.dir/build.make CMakeFiles/test_join.dir/list.cpp.o
.PHONY : list.cpp.o

list.i: list.cpp.i

.PHONY : list.i

# target to preprocess a source file
list.cpp.i:
	$(MAKE) -f CMakeFiles/test_radix.dir/build.make CMakeFiles/test_radix.dir/list.cpp.i
	$(MAKE) -f CMakeFiles/Project2019.dir/build.make CMakeFiles/Project2019.dir/list.cpp.i
	$(MAKE) -f CMakeFiles/test_join.dir/build.make CMakeFiles/test_join.dir/list.cpp.i
.PHONY : list.cpp.i

list.s: list.cpp.s

.PHONY : list.s

# target to generate assembly for a file
list.cpp.s:
	$(MAKE) -f CMakeFiles/test_radix.dir/build.make CMakeFiles/test_radix.dir/list.cpp.s
	$(MAKE) -f CMakeFiles/Project2019.dir/build.make CMakeFiles/Project2019.dir/list.cpp.s
	$(MAKE) -f CMakeFiles/test_join.dir/build.make CMakeFiles/test_join.dir/list.cpp.s
.PHONY : list.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/Project2019.dir/build.make CMakeFiles/Project2019.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/Project2019.dir/build.make CMakeFiles/Project2019.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/Project2019.dir/build.make CMakeFiles/Project2019.dir/main.cpp.s
.PHONY : main.cpp.s

query.o: query.cpp.o

.PHONY : query.o

# target to build an object file
query.cpp.o:
	$(MAKE) -f CMakeFiles/Project2019.dir/build.make CMakeFiles/Project2019.dir/query.cpp.o
.PHONY : query.cpp.o

query.i: query.cpp.i

.PHONY : query.i

# target to preprocess a source file
query.cpp.i:
	$(MAKE) -f CMakeFiles/Project2019.dir/build.make CMakeFiles/Project2019.dir/query.cpp.i
.PHONY : query.cpp.i

query.s: query.cpp.s

.PHONY : query.s

# target to generate assembly for a file
query.cpp.s:
	$(MAKE) -f CMakeFiles/Project2019.dir/build.make CMakeFiles/Project2019.dir/query.cpp.s
.PHONY : query.cpp.s

queue.o: queue.cpp.o

.PHONY : queue.o

# target to build an object file
queue.cpp.o:
	$(MAKE) -f CMakeFiles/Project2019.dir/build.make CMakeFiles/Project2019.dir/queue.cpp.o
	$(MAKE) -f CMakeFiles/test_jobscheduler.dir/build.make CMakeFiles/test_jobscheduler.dir/queue.cpp.o
	$(MAKE) -f CMakeFiles/test_queue.dir/build.make CMakeFiles/test_queue.dir/queue.cpp.o
.PHONY : queue.cpp.o

queue.i: queue.cpp.i

.PHONY : queue.i

# target to preprocess a source file
queue.cpp.i:
	$(MAKE) -f CMakeFiles/Project2019.dir/build.make CMakeFiles/Project2019.dir/queue.cpp.i
	$(MAKE) -f CMakeFiles/test_jobscheduler.dir/build.make CMakeFiles/test_jobscheduler.dir/queue.cpp.i
	$(MAKE) -f CMakeFiles/test_queue.dir/build.make CMakeFiles/test_queue.dir/queue.cpp.i
.PHONY : queue.cpp.i

queue.s: queue.cpp.s

.PHONY : queue.s

# target to generate assembly for a file
queue.cpp.s:
	$(MAKE) -f CMakeFiles/Project2019.dir/build.make CMakeFiles/Project2019.dir/queue.cpp.s
	$(MAKE) -f CMakeFiles/test_jobscheduler.dir/build.make CMakeFiles/test_jobscheduler.dir/queue.cpp.s
	$(MAKE) -f CMakeFiles/test_queue.dir/build.make CMakeFiles/test_queue.dir/queue.cpp.s
.PHONY : queue.cpp.s

radix.o: radix.cpp.o

.PHONY : radix.o

# target to build an object file
radix.cpp.o:
	$(MAKE) -f CMakeFiles/test_radix.dir/build.make CMakeFiles/test_radix.dir/radix.cpp.o
	$(MAKE) -f CMakeFiles/Project2019.dir/build.make CMakeFiles/Project2019.dir/radix.cpp.o
	$(MAKE) -f CMakeFiles/test_join.dir/build.make CMakeFiles/test_join.dir/radix.cpp.o
.PHONY : radix.cpp.o

radix.i: radix.cpp.i

.PHONY : radix.i

# target to preprocess a source file
radix.cpp.i:
	$(MAKE) -f CMakeFiles/test_radix.dir/build.make CMakeFiles/test_radix.dir/radix.cpp.i
	$(MAKE) -f CMakeFiles/Project2019.dir/build.make CMakeFiles/Project2019.dir/radix.cpp.i
	$(MAKE) -f CMakeFiles/test_join.dir/build.make CMakeFiles/test_join.dir/radix.cpp.i
.PHONY : radix.cpp.i

radix.s: radix.cpp.s

.PHONY : radix.s

# target to generate assembly for a file
radix.cpp.s:
	$(MAKE) -f CMakeFiles/test_radix.dir/build.make CMakeFiles/test_radix.dir/radix.cpp.s
	$(MAKE) -f CMakeFiles/Project2019.dir/build.make CMakeFiles/Project2019.dir/radix.cpp.s
	$(MAKE) -f CMakeFiles/test_join.dir/build.make CMakeFiles/test_join.dir/radix.cpp.s
.PHONY : radix.cpp.s

relation.o: relation.cpp.o

.PHONY : relation.o

# target to build an object file
relation.cpp.o:
	$(MAKE) -f CMakeFiles/test_radix.dir/build.make CMakeFiles/test_radix.dir/relation.cpp.o
	$(MAKE) -f CMakeFiles/Project2019.dir/build.make CMakeFiles/Project2019.dir/relation.cpp.o
	$(MAKE) -f CMakeFiles/test_join.dir/build.make CMakeFiles/test_join.dir/relation.cpp.o
.PHONY : relation.cpp.o

relation.i: relation.cpp.i

.PHONY : relation.i

# target to preprocess a source file
relation.cpp.i:
	$(MAKE) -f CMakeFiles/test_radix.dir/build.make CMakeFiles/test_radix.dir/relation.cpp.i
	$(MAKE) -f CMakeFiles/Project2019.dir/build.make CMakeFiles/Project2019.dir/relation.cpp.i
	$(MAKE) -f CMakeFiles/test_join.dir/build.make CMakeFiles/test_join.dir/relation.cpp.i
.PHONY : relation.cpp.i

relation.s: relation.cpp.s

.PHONY : relation.s

# target to generate assembly for a file
relation.cpp.s:
	$(MAKE) -f CMakeFiles/test_radix.dir/build.make CMakeFiles/test_radix.dir/relation.cpp.s
	$(MAKE) -f CMakeFiles/Project2019.dir/build.make CMakeFiles/Project2019.dir/relation.cpp.s
	$(MAKE) -f CMakeFiles/test_join.dir/build.make CMakeFiles/test_join.dir/relation.cpp.s
.PHONY : relation.cpp.s

relations.o: relations.cpp.o

.PHONY : relations.o

# target to build an object file
relations.cpp.o:
	$(MAKE) -f CMakeFiles/Project2019.dir/build.make CMakeFiles/Project2019.dir/relations.cpp.o
	$(MAKE) -f CMakeFiles/test_join.dir/build.make CMakeFiles/test_join.dir/relations.cpp.o
.PHONY : relations.cpp.o

relations.i: relations.cpp.i

.PHONY : relations.i

# target to preprocess a source file
relations.cpp.i:
	$(MAKE) -f CMakeFiles/Project2019.dir/build.make CMakeFiles/Project2019.dir/relations.cpp.i
	$(MAKE) -f CMakeFiles/test_join.dir/build.make CMakeFiles/test_join.dir/relations.cpp.i
.PHONY : relations.cpp.i

relations.s: relations.cpp.s

.PHONY : relations.s

# target to generate assembly for a file
relations.cpp.s:
	$(MAKE) -f CMakeFiles/Project2019.dir/build.make CMakeFiles/Project2019.dir/relations.cpp.s
	$(MAKE) -f CMakeFiles/test_join.dir/build.make CMakeFiles/test_join.dir/relations.cpp.s
.PHONY : relations.cpp.s

results_list.o: results_list.cpp.o

.PHONY : results_list.o

# target to build an object file
results_list.cpp.o:
	$(MAKE) -f CMakeFiles/Project2019.dir/build.make CMakeFiles/Project2019.dir/results_list.cpp.o
	$(MAKE) -f CMakeFiles/test_join.dir/build.make CMakeFiles/test_join.dir/results_list.cpp.o
.PHONY : results_list.cpp.o

results_list.i: results_list.cpp.i

.PHONY : results_list.i

# target to preprocess a source file
results_list.cpp.i:
	$(MAKE) -f CMakeFiles/Project2019.dir/build.make CMakeFiles/Project2019.dir/results_list.cpp.i
	$(MAKE) -f CMakeFiles/test_join.dir/build.make CMakeFiles/test_join.dir/results_list.cpp.i
.PHONY : results_list.cpp.i

results_list.s: results_list.cpp.s

.PHONY : results_list.s

# target to generate assembly for a file
results_list.cpp.s:
	$(MAKE) -f CMakeFiles/Project2019.dir/build.make CMakeFiles/Project2019.dir/results_list.cpp.s
	$(MAKE) -f CMakeFiles/test_join.dir/build.make CMakeFiles/test_join.dir/results_list.cpp.s
.PHONY : results_list.cpp.s

rows_array.o: rows_array.cpp.o

.PHONY : rows_array.o

# target to build an object file
rows_array.cpp.o:
	$(MAKE) -f CMakeFiles/test_radix.dir/build.make CMakeFiles/test_radix.dir/rows_array.cpp.o
	$(MAKE) -f CMakeFiles/Project2019.dir/build.make CMakeFiles/Project2019.dir/rows_array.cpp.o
	$(MAKE) -f CMakeFiles/test_join.dir/build.make CMakeFiles/test_join.dir/rows_array.cpp.o
.PHONY : rows_array.cpp.o

rows_array.i: rows_array.cpp.i

.PHONY : rows_array.i

# target to preprocess a source file
rows_array.cpp.i:
	$(MAKE) -f CMakeFiles/test_radix.dir/build.make CMakeFiles/test_radix.dir/rows_array.cpp.i
	$(MAKE) -f CMakeFiles/Project2019.dir/build.make CMakeFiles/Project2019.dir/rows_array.cpp.i
	$(MAKE) -f CMakeFiles/test_join.dir/build.make CMakeFiles/test_join.dir/rows_array.cpp.i
.PHONY : rows_array.cpp.i

rows_array.s: rows_array.cpp.s

.PHONY : rows_array.s

# target to generate assembly for a file
rows_array.cpp.s:
	$(MAKE) -f CMakeFiles/test_radix.dir/build.make CMakeFiles/test_radix.dir/rows_array.cpp.s
	$(MAKE) -f CMakeFiles/Project2019.dir/build.make CMakeFiles/Project2019.dir/rows_array.cpp.s
	$(MAKE) -f CMakeFiles/test_join.dir/build.make CMakeFiles/test_join.dir/rows_array.cpp.s
.PHONY : rows_array.cpp.s

sort.o: sort.cpp.o

.PHONY : sort.o

# target to build an object file
sort.cpp.o:
	$(MAKE) -f CMakeFiles/test_radix.dir/build.make CMakeFiles/test_radix.dir/sort.cpp.o
	$(MAKE) -f CMakeFiles/Project2019.dir/build.make CMakeFiles/Project2019.dir/sort.cpp.o
	$(MAKE) -f CMakeFiles/test_join.dir/build.make CMakeFiles/test_join.dir/sort.cpp.o
.PHONY : sort.cpp.o

sort.i: sort.cpp.i

.PHONY : sort.i

# target to preprocess a source file
sort.cpp.i:
	$(MAKE) -f CMakeFiles/test_radix.dir/build.make CMakeFiles/test_radix.dir/sort.cpp.i
	$(MAKE) -f CMakeFiles/Project2019.dir/build.make CMakeFiles/Project2019.dir/sort.cpp.i
	$(MAKE) -f CMakeFiles/test_join.dir/build.make CMakeFiles/test_join.dir/sort.cpp.i
.PHONY : sort.cpp.i

sort.s: sort.cpp.s

.PHONY : sort.s

# target to generate assembly for a file
sort.cpp.s:
	$(MAKE) -f CMakeFiles/test_radix.dir/build.make CMakeFiles/test_radix.dir/sort.cpp.s
	$(MAKE) -f CMakeFiles/Project2019.dir/build.make CMakeFiles/Project2019.dir/sort.cpp.s
	$(MAKE) -f CMakeFiles/test_join.dir/build.make CMakeFiles/test_join.dir/sort.cpp.s
.PHONY : sort.cpp.s

stack.o: stack.cpp.o

.PHONY : stack.o

# target to build an object file
stack.cpp.o:
	$(MAKE) -f CMakeFiles/test_radix.dir/build.make CMakeFiles/test_radix.dir/stack.cpp.o
	$(MAKE) -f CMakeFiles/Project2019.dir/build.make CMakeFiles/Project2019.dir/stack.cpp.o
	$(MAKE) -f CMakeFiles/test_join.dir/build.make CMakeFiles/test_join.dir/stack.cpp.o
.PHONY : stack.cpp.o

stack.i: stack.cpp.i

.PHONY : stack.i

# target to preprocess a source file
stack.cpp.i:
	$(MAKE) -f CMakeFiles/test_radix.dir/build.make CMakeFiles/test_radix.dir/stack.cpp.i
	$(MAKE) -f CMakeFiles/Project2019.dir/build.make CMakeFiles/Project2019.dir/stack.cpp.i
	$(MAKE) -f CMakeFiles/test_join.dir/build.make CMakeFiles/test_join.dir/stack.cpp.i
.PHONY : stack.cpp.i

stack.s: stack.cpp.s

.PHONY : stack.s

# target to generate assembly for a file
stack.cpp.s:
	$(MAKE) -f CMakeFiles/test_radix.dir/build.make CMakeFiles/test_radix.dir/stack.cpp.s
	$(MAKE) -f CMakeFiles/Project2019.dir/build.make CMakeFiles/Project2019.dir/stack.cpp.s
	$(MAKE) -f CMakeFiles/test_join.dir/build.make CMakeFiles/test_join.dir/stack.cpp.s
.PHONY : stack.cpp.s

test_bitmap.o: test_bitmap.cpp.o

.PHONY : test_bitmap.o

# target to build an object file
test_bitmap.cpp.o:
	$(MAKE) -f CMakeFiles/test_bitmap.dir/build.make CMakeFiles/test_bitmap.dir/test_bitmap.cpp.o
.PHONY : test_bitmap.cpp.o

test_bitmap.i: test_bitmap.cpp.i

.PHONY : test_bitmap.i

# target to preprocess a source file
test_bitmap.cpp.i:
	$(MAKE) -f CMakeFiles/test_bitmap.dir/build.make CMakeFiles/test_bitmap.dir/test_bitmap.cpp.i
.PHONY : test_bitmap.cpp.i

test_bitmap.s: test_bitmap.cpp.s

.PHONY : test_bitmap.s

# target to generate assembly for a file
test_bitmap.cpp.s:
	$(MAKE) -f CMakeFiles/test_bitmap.dir/build.make CMakeFiles/test_bitmap.dir/test_bitmap.cpp.s
.PHONY : test_bitmap.cpp.s

test_jobscheduler.o: test_jobscheduler.cpp.o

.PHONY : test_jobscheduler.o

# target to build an object file
test_jobscheduler.cpp.o:
	$(MAKE) -f CMakeFiles/test_jobscheduler.dir/build.make CMakeFiles/test_jobscheduler.dir/test_jobscheduler.cpp.o
.PHONY : test_jobscheduler.cpp.o

test_jobscheduler.i: test_jobscheduler.cpp.i

.PHONY : test_jobscheduler.i

# target to preprocess a source file
test_jobscheduler.cpp.i:
	$(MAKE) -f CMakeFiles/test_jobscheduler.dir/build.make CMakeFiles/test_jobscheduler.dir/test_jobscheduler.cpp.i
.PHONY : test_jobscheduler.cpp.i

test_jobscheduler.s: test_jobscheduler.cpp.s

.PHONY : test_jobscheduler.s

# target to generate assembly for a file
test_jobscheduler.cpp.s:
	$(MAKE) -f CMakeFiles/test_jobscheduler.dir/build.make CMakeFiles/test_jobscheduler.dir/test_jobscheduler.cpp.s
.PHONY : test_jobscheduler.cpp.s

test_join.o: test_join.cpp.o

.PHONY : test_join.o

# target to build an object file
test_join.cpp.o:
	$(MAKE) -f CMakeFiles/test_join.dir/build.make CMakeFiles/test_join.dir/test_join.cpp.o
.PHONY : test_join.cpp.o

test_join.i: test_join.cpp.i

.PHONY : test_join.i

# target to preprocess a source file
test_join.cpp.i:
	$(MAKE) -f CMakeFiles/test_join.dir/build.make CMakeFiles/test_join.dir/test_join.cpp.i
.PHONY : test_join.cpp.i

test_join.s: test_join.cpp.s

.PHONY : test_join.s

# target to generate assembly for a file
test_join.cpp.s:
	$(MAKE) -f CMakeFiles/test_join.dir/build.make CMakeFiles/test_join.dir/test_join.cpp.s
.PHONY : test_join.cpp.s

test_queue.o: test_queue.cpp.o

.PHONY : test_queue.o

# target to build an object file
test_queue.cpp.o:
	$(MAKE) -f CMakeFiles/test_queue.dir/build.make CMakeFiles/test_queue.dir/test_queue.cpp.o
.PHONY : test_queue.cpp.o

test_queue.i: test_queue.cpp.i

.PHONY : test_queue.i

# target to preprocess a source file
test_queue.cpp.i:
	$(MAKE) -f CMakeFiles/test_queue.dir/build.make CMakeFiles/test_queue.dir/test_queue.cpp.i
.PHONY : test_queue.cpp.i

test_queue.s: test_queue.cpp.s

.PHONY : test_queue.s

# target to generate assembly for a file
test_queue.cpp.s:
	$(MAKE) -f CMakeFiles/test_queue.dir/build.make CMakeFiles/test_queue.dir/test_queue.cpp.s
.PHONY : test_queue.cpp.s

test_radix.o: test_radix.cpp.o

.PHONY : test_radix.o

# target to build an object file
test_radix.cpp.o:
	$(MAKE) -f CMakeFiles/test_radix.dir/build.make CMakeFiles/test_radix.dir/test_radix.cpp.o
.PHONY : test_radix.cpp.o

test_radix.i: test_radix.cpp.i

.PHONY : test_radix.i

# target to preprocess a source file
test_radix.cpp.i:
	$(MAKE) -f CMakeFiles/test_radix.dir/build.make CMakeFiles/test_radix.dir/test_radix.cpp.i
.PHONY : test_radix.cpp.i

test_radix.s: test_radix.cpp.s

.PHONY : test_radix.s

# target to generate assembly for a file
test_radix.cpp.s:
	$(MAKE) -f CMakeFiles/test_radix.dir/build.make CMakeFiles/test_radix.dir/test_radix.cpp.s
.PHONY : test_radix.cpp.s

test_relations.o: test_relations.cpp.o

.PHONY : test_relations.o

# target to build an object file
test_relations.cpp.o:
	$(MAKE) -f CMakeFiles/test_relations.dir/build.make CMakeFiles/test_relations.dir/test_relations.cpp.o
.PHONY : test_relations.cpp.o

test_relations.i: test_relations.cpp.i

.PHONY : test_relations.i

# target to preprocess a source file
test_relations.cpp.i:
	$(MAKE) -f CMakeFiles/test_relations.dir/build.make CMakeFiles/test_relations.dir/test_relations.cpp.i
.PHONY : test_relations.cpp.i

test_relations.s: test_relations.cpp.s

.PHONY : test_relations.s

# target to generate assembly for a file
test_relations.cpp.s:
	$(MAKE) -f CMakeFiles/test_relations.dir/build.make CMakeFiles/test_relations.dir/test_relations.cpp.s
.PHONY : test_relations.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... test_bitmap"
	@echo "... test_radix"
	@echo "... Project2019"
	@echo "... edit_cache"
	@echo "... test_relations"
	@echo "... test_jobscheduler"
	@echo "... test_join"
	@echo "... test_queue"
	@echo "... JoinArray.o"
	@echo "... JoinArray.i"
	@echo "... JoinArray.s"
	@echo "... Priority_Queue.o"
	@echo "... Priority_Queue.i"
	@echo "... Priority_Queue.s"
	@echo "... SQL.o"
	@echo "... SQL.i"
	@echo "... SQL.s"
	@echo "... SQLInfo.o"
	@echo "... SQLInfo.i"
	@echo "... SQLInfo.s"
	@echo "... do_query.o"
	@echo "... do_query.i"
	@echo "... do_query.s"
	@echo "... job.o"
	@echo "... job.i"
	@echo "... job.s"
	@echo "... jobscheduler.o"
	@echo "... jobscheduler.i"
	@echo "... jobscheduler.s"
	@echo "... join_preds.o"
	@echo "... join_preds.i"
	@echo "... join_preds.s"
	@echo "... list.o"
	@echo "... list.i"
	@echo "... list.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... query.o"
	@echo "... query.i"
	@echo "... query.s"
	@echo "... queue.o"
	@echo "... queue.i"
	@echo "... queue.s"
	@echo "... radix.o"
	@echo "... radix.i"
	@echo "... radix.s"
	@echo "... relation.o"
	@echo "... relation.i"
	@echo "... relation.s"
	@echo "... relations.o"
	@echo "... relations.i"
	@echo "... relations.s"
	@echo "... results_list.o"
	@echo "... results_list.i"
	@echo "... results_list.s"
	@echo "... rows_array.o"
	@echo "... rows_array.i"
	@echo "... rows_array.s"
	@echo "... sort.o"
	@echo "... sort.i"
	@echo "... sort.s"
	@echo "... stack.o"
	@echo "... stack.i"
	@echo "... stack.s"
	@echo "... test_bitmap.o"
	@echo "... test_bitmap.i"
	@echo "... test_bitmap.s"
	@echo "... test_jobscheduler.o"
	@echo "... test_jobscheduler.i"
	@echo "... test_jobscheduler.s"
	@echo "... test_join.o"
	@echo "... test_join.i"
	@echo "... test_join.s"
	@echo "... test_queue.o"
	@echo "... test_queue.i"
	@echo "... test_queue.s"
	@echo "... test_radix.o"
	@echo "... test_radix.i"
	@echo "... test_radix.s"
	@echo "... test_relations.o"
	@echo "... test_relations.i"
	@echo "... test_relations.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

